# Generated by Django 3.0.6 on 2020-05-23 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=5)),
                ('projection', models.IntegerField()),
                ('points', models.IntegerField()),
                ('drafted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('number', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draft.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueId', models.IntegerField()),
                ('teams', models.IntegerField()),
                ('rounds', models.IntegerField()),
                ('picks', models.ManyToManyField(to='draft.Pick')),
                ('players', models.ManyToManyField(to='draft.Player')),
            ],
        ),
    ]
