# Generated by Django 3.0.6 on 2020-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='owner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
